swagger: "2.0"
info:
  title: E-Commerce
  version: 1.0.0
paths:
  paths:
  /api/v1/register:
    post:
      tags:
        - User
      summary: Register a new user
      description: Create a new user account with name, email, password, and image fields.
      consumes:
        - multipart/form-data
      produces:
        - application/json
      parameters:
        - in: formData
          name: name
          type: string
          required: true
          description: User's name
        - in: formData
          name: email
          type: string
          required: true
          description: User's email
        - in: formData
          name: password
          type: string
          format: password
          required: true
          description: User's password
        - in: formData
          name: avatar
          type: file
          required: true
          description: User's profile image
      responses:
        "201":
          description: Created
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
  /api/v1/login:
    post:
      tags:
        - User
      summary: User login
      description: Authenticate user with email and password.
      consumes:
        - multipart/form-data
      produces:
        - application/json
      parameters:
        - in: formData
          name: email
          type: string
          required: true
          description: User's email
        - in: formData
          name: password
          type: string
          format: password
          required: true
          description: User's password
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error

  /api/v1/logout:
    get:
      tags:
        - User
      summary: Log out a user
      description: Logs out the currently authenticated user
      responses:
        "200":
          description: OK
        "401":
          description: Unauthorized
      security:
        - BearerAuth: []

  /api/v1/password/forgot:
    post:
      tags:
        - User
      summary: Forgot Your password
      description: Check By Email
      consumes:
        - multipart/form-data
      produces:
        - application/json
      parameters:
        - in: formData
          name: email
          type: string
          required: true
          description: User's email
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error

  /api/v1/password/reset/{token}:
    put:
      tags:
        - User
      summary: Reset Password
      description: Reset user password using the provided reset token.
      parameters:
        - in: path
          name: token
          description: Reset token received via email.
          required: true
          schema:
            type: string
        - in: formData
          name: newPassword
          description: New password for the user.
          required: true
          type: string
        - in: formData
          name: confirmPassword
          description: Confirm password for the user.
          required: true
          type: string
      responses:
        "200":
          description: Password reset successful.
        "400":
          description: Bad Request - Invalid or expired token.
        "500":
          description: Internal Server Error.
